version: '3.18'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ['start-dev']
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin