version: '3.18'

services:
#  mongodb:
#    container_name: mongo_demo
#    image: mongo
#    restart: on-failure
#    ports:
#      - 27017:27017
#    volumes:
#      - ./data:/data/db
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ['start-dev']
    ports:
      - "8099:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin